service: serverless-develop-basic-demo

plugins:
<<<<<<< HEAD
  - /Users/Rafal/Node/serverless-develop/index # Change to your absolute dir :P
=======
  - serverless-develop
>>>>>>> 8cfae539003fffcd902b0ff40036107091942a69

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: withDependency.hello
    events:
        - http: GET /with
  handler2:
    handler: withoutDependency.hello
    events:
        - http: GET /without
